version: '3.8'

volumes:
  db:
    driver: local
services:
  kcd-dev-mysql:
    container_name: kcd-dev-mysql
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  kcd-ad-platform:
    container_name: kcd-ad-platform
    image: kcd-ad-platform:1.5
    restart: no
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://kcd-dev-mysql:3306/kcd?autoReconnect=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kcd-dev-mysql